### ISSUE TITLE
Listen for attribute change crashes the editor

### ISSUE THREAD

**Issue by MortenTobiasNielsen** [tranek/GASShooter#10]
Hi

First of all thanks for the great work you have done with the project. 

**Edit:** I just realised that this is a known issue with 4.25. The issue has just been resolved with 4.25.1. I will keep the issue open in case you need to know - you can close the issue when you read this. :)

I have been inspecting the UI_HUD and found the "Listen for attribute change" function, which seems like a good way to track all the attributes for the UI. I am unfortunately getting an error when I try to save the UI_HUD and I get the same problem, when I try to use it in my own project:
![Error](https://user-images.githubusercontent.com/48355480/83607091-e385a080-a57a-11ea-8117-fe2e54893b83.png)

On further inspection it seems that the problem doesn't reside with the "Listen for attribute change" function, but instead when attributes are accessed. I get the same error when I use "Float attribute from ability system component":
![Error2](https://user-images.githubusercontent.com/48355480/83610887-74ab4600-a580-11ea-8d82-454c999a8321.png)
 
A related question: 
Is it a good idea to have this task living with the game state? What if you have 100's or 1000's of players in the same world - wouldn't that mean that the game state have as many async calls? 

Best regards,
Morten

**Comment by tranek** [comment]
4.25.1 was released today fixing the crash.

> Is it a good idea to have this task living with the game state? What if you have 100's or 1000's of players in the same world - wouldn't that mean that the game state have as many async calls?

I have not used it in the GameState so I can't give you an affirmative answer one way or another. There would be an async call for each task that you create, yes. They're essentially a wrapper around the ASC's delegates. So if you already bind to all 100-1000 ASCs in the GameState and it works okay then I don't imagine this would be much worse other than more memory usage versus just binding to all the ASC delegates in C++.
