### ISSUE TITLE
GSWeapon Crash

### ISSUE THREAD

**Issue by narthur157** [tranek/GASShooter#12]
`AGSWeapon` crashes during level changes, as it uses a destructor rather than `BeginDestroy`

See `~AGSWeapon()`

**Comment by tranek** [comment]
Would you please add reproduction steps?

Calling OpenLevel from BP to an empty map works fine in PIE and standalone for me.

**Comment by narthur157** [comment]
I would have thought that would cause the issue as well. I'm not 100% sure how to reproduce it in that case, as it's likely specific to the transition sequence in my project forked from this. 

For me switching over the de-initialization over to BeginDestroy fixed the issue, and seems to make sense generally as this is the proper "teardown" phase for the object rather than when UE decides to run garbage collection

**Comment by tranek** [comment]
Since it's an `AActor`, I prefer` EndPlay` over `BeginDestroy`. I think I just had destructors on my mind when I wrote it. Thanks for bringing it to my attention!
