### ISSUE TITLE
There's no overridden FGameplayEffectContext

### ISSUE THREAD

**Issue by jwatte** [tranek/GASShooter#27]
The documentation says:

  > Subclassing FGameplayEffectContext to send additional information to GameplayCues

However, I can't find any such subclassing, either in this project, nor in GASDocumentation.
Is this a TODO item?
Did not not work, and the documentation should be removed?

**Comment by tranek** [comment]
https://github.com/tranek/GASShooter/blob/master/Source/GASShooter/Public/Characters/Abilities/GSGameplayEffectTypes.h#L15

**Comment by jwatte** [comment]
You are right. I just can't search. (`rg` immediately picked it up; should have tried that from the beginning.)

Thanks for the pointer!
