### ISSUE TITLE
When possessing a new pawn crash from WaitInteractableTarget::PerformTrace()

### ISSUE THREAD

**Issue by decryptedchaos** [tranek/GASShooter#29]
Is this actually an issue with the sphere trace  or something else,  I'm pulling my hair out over it right now because i want to implement a simple vehicle system. and anytime i possess the vehicle bang crash.  

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000000

UE4Editor_GASShooter!UGSAT_WaitInteractableTarget::PerformTrace() [C:\Users\joshk\source\repos\GASShooter\Source\GASShooter\Private\Characters\Abilities\AbilityTasks\GSAT_WaitInteractableTarget.cpp:196]
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_UnrealEd
UE4Editor_UnrealEd
UE4Editor
UE4Editor
UE4Editor
UE4Editor
UE4Editor
kernel32
ntdll

**Comment by tranek** [comment]
Hello, these Issues are for problems with the GASShooter sample project as is and not for tech support with other projects.

For help with your projects, please try one of these:

- [Unreal Slackers Discord](https://unrealslackers.org/)
- [Unreal Engine Forums](https://forums.unrealengine.com/)
- [Unreal Engine AnswerHub](https://answers.unrealengine.com/index.html)
