### ISSUE TITLE
Batching Suggestion

### ISSUE THREAD

**Issue by hojjatjafary** [tranek/GASShooter#40]
Instead of having another ability to run the instant one in batch mode, for example the `GA_RiflePrimary`, we can batch the abilities when they are activating by input, so we can modify the [AbilityLocalInputPressed ](https://github.com/tranek/GASShooter/blob/master/Source/GASShooter/Private/Characters/Abilities/GSAbilitySystemComponent.cpp#L123)like this:

```cpp
if (GA && GA->bActivateOnInput)
{
    if (GA->bBatchActivation)
    {
	FScopedServerAbilityRPCBatcher GSAbilityRPCBatcher(this, Spec.Handle);
	TryActivateAbility(Spec.Handle);
    }
    else
    {
	// Ability is not active, so try to activate it
	TryActivateAbility(Spec.Handle);
    }
}
```

**Comment by tranek** [comment]
That's closer to how Fortnite does it and probably Lyra (I haven't looked yet). This project was an exercise in how to do everything with abilities. This project is also iceboxed for now so I won't be implementing it. Thank you for the suggestion!
