### ISSUE TITLE
Implements crouching 

### ISSUE THREAD

**Issue by SalahAdDin** [tranek/GASShooter#8]
Have you thought about adding the possibility of crouching? I have seen the system you use to do Sprint and Jump a little complex, and I think it would be a little complex to do crouch, or roll, for example.

Thanks for this great template.

**Comment by tranek** [comment]
Unfortunately the character's skeletal mesh from Epic's ShooterGame does not come with animations for those so it's not possible to add them. The skeleton isn't the mannequin's skeleton either.

**Comment by SalahAdDin** [comment]
Can you guıde us about doıng ıt? Because ı am seeıng some tutorıals about ıt and ıt ıs possıble to do ıt wıth the default Unreal Engıne's mannequin.
